FROM node:slim AS builder

WORKDIR /app
COPY package*.json ./
COPY ./public ./public
COPY ./src ./src
RUN npm install
RUN npm run build

FROM node:alpine
WORKDIR /app
COPY --from=builder ./app/build ./build

EXPOSE 3000
CMD ["npx","serve", "-s", "build", "-l", "3000"]
